--
-- Para el cliente de DB se ejecuta las siguientes 3 lineas
--

ALTER USER 'root'@'localhost' IDENTIFIED BY 'adminSQL123'; 
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'adminSQL123';
FLUSH PRIVILEGES;


-- MySQL Script generated by MySQL Workbench
-- Sat Jan 16 18:51:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myAirportDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myAirportDb` ;

-- -----------------------------------------------------
-- Schema myAirportDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myAirportDb` DEFAULT CHARACTER SET utf8 ;
USE `myAirportDb` ;

-- -----------------------------------------------------
-- Table `myAirportDb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myAirportDb`.`user` ;

CREATE TABLE IF NOT EXISTS `myAirportDb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `document` VARCHAR(10) NOT NULL,
  `password` VARCHAR(95) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `document_UNIQUE` ON `myAirportDb`.`user` (`document` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `myAirportDb`.`airline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myAirportDb`.`airline` ;

CREATE TABLE IF NOT EXISTS `myAirportDb`.`airline` (
  `idairline` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idairline`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `myAirportDb`.`airline` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `myAirportDb`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myAirportDb`.`schedule` ;

CREATE TABLE IF NOT EXISTS `myAirportDb`.`schedule` (
  `idschedule` INT NOT NULL AUTO_INCREMENT,
  `date_schedule` DATETIME NOT NULL,
  PRIMARY KEY (`idschedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myAirportDb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myAirportDb`.`city` ;

CREATE TABLE IF NOT EXISTS `myAirportDb`.`city` (
  `idcity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myAirportDb`.`flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myAirportDb`.`flight` ;

CREATE TABLE IF NOT EXISTS `myAirportDb`.`flight` (
  `idflight` INT NOT NULL AUTO_INCREMENT,
  `origin_idcity` INT NOT NULL,
  `destination_idcity` INT NOT NULL,
  PRIMARY KEY (`idflight`, `origin_idcity`, `destination_idcity`),
  CONSTRAINT `fk_flight_city1`
    FOREIGN KEY (`origin_idcity`)
    REFERENCES `myAirportDb`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_city2`
    FOREIGN KEY (`destination_idcity`)
    REFERENCES `myAirportDb`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_flight_city1_idx` ON `myAirportDb`.`flight` (`origin_idcity` ASC) VISIBLE;

CREATE INDEX `fk_flight_city2_idx` ON `myAirportDb`.`flight` (`destination_idcity` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `myAirportDb`.`rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myAirportDb`.`rate` ;

CREATE TABLE IF NOT EXISTS `myAirportDb`.`rate` (
  `idrate` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM("C", "E", "A") NOT NULL DEFAULT 'A',
  `airline_idairline` INT NOT NULL,
  `space_available` INT NOT NULL,
  `price` INT NOT NULL,
  `schedule_idschedule` INT NOT NULL,
  `flight_idflight` INT NOT NULL,
  PRIMARY KEY (`idrate`, `airline_idairline`, `schedule_idschedule`, `flight_idflight`),
  CONSTRAINT `fk_flig_has_sch_has_airl_airline1`
    FOREIGN KEY (`airline_idairline`)
    REFERENCES `myAirportDb`.`airline` (`idairline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flig_has_sch_has_airl_schedule1`
    FOREIGN KEY (`schedule_idschedule`)
    REFERENCES `myAirportDb`.`schedule` (`idschedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flig_has_sch_has_airl_flight1`
    FOREIGN KEY (`flight_idflight`)
    REFERENCES `myAirportDb`.`flight` (`idflight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_flig_has_sch_has_airl_airline1_idx` ON `myAirportDb`.`rate` (`airline_idairline` ASC) VISIBLE;

CREATE INDEX `fk_flig_has_sch_has_airl_schedule1_idx` ON `myAirportDb`.`rate` (`schedule_idschedule` ASC) VISIBLE;

CREATE INDEX `fk_flig_has_sch_has_airl_flight1_idx` ON `myAirportDb`.`rate` (`flight_idflight` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `myAirportDb`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myAirportDb`.`booking` ;

CREATE TABLE IF NOT EXISTS `myAirportDb`.`booking` (
  `idbooking` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `rates_idrate` INT NOT NULL,
  PRIMARY KEY (`idbooking`, `user_iduser`, `rates_idrate`),
  CONSTRAINT `fk_booking_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `myAirportDb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_rates1`
    FOREIGN KEY (`rates_idrate`)
    REFERENCES `myAirportDb`.`rate` (`idrate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_booking_user_idx` ON `myAirportDb`.`booking` (`user_iduser` ASC) VISIBLE;

CREATE INDEX `fk_booking_rates1_idx` ON `myAirportDb`.`booking` (`rates_idrate` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -------------
-- Inserción de datos en la tabla ciudades
-- -----------

insert into city set  name = 'Cali';
insert into city set  name = 'Bogotá';
insert into city set  name = 'Medellín';

-- -------------
-- Inserción de datos en la tabla Vuelos
-- -----------
insert into flight set origin_idcity= 1,  destination_idcity= 2;
insert into flight set origin_idcity= 2,  destination_idcity= 1;
insert into flight set origin_idcity= 3,  destination_idcity= 1;

-- -------------
-- Inserción de datos en la tabla Aerolineas
-- -------------
insert into city set  name = 'Cali';
insert into airline set  name= 'Viva Air';
insert into airline set  name= 'Wingo';
insert into airline set  name= 'AirLine';
insert into airline set  name= 'Avianca';
insert into airline set  name= 'SATENA';

--
-- Inserción en la tabal horarios
--
insert into schedule set date_schedule='2021-2-22 13:15:00';
insert into schedule set date_schedule='2021-2-18 15:15:00';
insert into schedule set date_schedule='2021-2-19 03:15:00';
insert into schedule set date_schedule='2021-2-20 04:15:00';
insert into schedule set date_schedule='2021-2-21 05:15:00';

--
-- Insert in table Rates
--
insert into rate
            set status='C',space_available= 23,price= 10000,airline_idairline = 1,
                schedule_idschedule=4,flight_idflight=2;
insert into rate
            set status='E',space_available= 3,price= 18000,airline_idairline = 3,
                schedule_idschedule=4,flight_idflight=2;
insert into rate
            set status='A',space_available= 32,price= 70000,airline_idairline = 1,
                schedule_idschedule=1,flight_idflight=2;
insert into rate
            set status='C',space_available= 14,price= 90000,airline_idairline = 2,
                schedule_idschedule=2,flight_idflight=2;
insert into rate
            set status='C',space_available= 8,price= 150000,airline_idairline = 4,
                schedule_idschedule=4,flight_idflight=2;

insert into rate
            set status='C',space_available= 23,price= 10000,airline_idairline = 1,
                schedule_idschedule=4,flight_idflight=2;
insert into rate
            set status='A',space_available= 34,price= 10000,airline_idairline = 1,
                schedule_idschedule=4,flight_idflight=3;
insert into rate
            set status='A',space_available= 24,price= 10000,airline_idairline = 2,
                schedule_idschedule=4,flight_idflight=1;
insert into rate
            set status='A',space_available= 4,price= 19000,airline_idairline = 3,
                schedule_idschedule=4,flight_idflight=3;
--
-- 